custom_admin_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: CustomAdminBundle:Default:index }

admin_user_import:
    pattern:  /user/import/
    defaults: { _controller: CustomAdminBundle:UserImporter:importUserInfoByExcel }

admin_user_import_to_base:
    pattern:  /user/import/to/base
    defaults: { _controller: CustomAdminBundle:UserImporter:importUserDataToBase }



admin_user:
    pattern:  /user
    defaults: { _controller: CustomAdminBundle:User:index }

admin_user_edit:
    pattern:  /user/{id}/edit
    defaults: { _controller: CustomAdminBundle:User:edit }

admin_user_show:
    pattern:  /user/{id}
    defaults: { _controller: CustomAdminBundle:User:show }
admin_organization:
    pattern:  /organization
    defaults: { _controller: CustomAdminBundle:Organization:index }
admin_organization_create:
    pattern:  /organization/create
    defaults: { _controller: CustomAdminBundle:Organization:create }

admin_organization_edit:
    pattern:  /organization/edit
    defaults: { _controller: CustomAdminBundle:Organization:edit }
admin_organization_delete:
    pattern:  /organization/delete
    defaults: { _controller: CustomAdminBundle:Organization:delete }
admin_organization_select_modal:
    pattern:  /organization/select/modal
    defaults: { _controller: CustomAdminBundle:Organization:selectModal }

admin_user_learn_data:
    pattern:  /user/learn/data
    defaults: { _controller: CustomAdminBundle:UserLearnData:index }
admin_user_learn_data_exp_confirm:
    pattern:  /user/learn/data/export/confirm
    defaults: { _controller: CustomAdminBundle:UserLearnData:exportConfirm }
admin_user_learn_data_exp:
    pattern:  /user/learn/data/export
    defaults: { _controller: CustomAdminBundle:UserLearnData:export }


admin_course_match:
    pattern:  /course/match
    defaults: { _controller: CustomAdminBundle:CourseMatch:match }


organization_user_list:
    pattern:  /organization/user/list
    defaults: { _controller: CustomAdminBundle:Organization:userList }
