parameters:
#    classroom.example.class: Classroom\ClassroomBundle\Example

services:
#    classroom.example:
#        class: %classroom.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
